/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../components/shared.module';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from '@angular/core/src/i18n/tokens';
import * as import4 from '@angular/core/src/render/api';
import * as import5 from '@angular/core/src/linker/view';
import * as import6 from '@angular/core/src/linker/element';
import * as import7 from '@angular/core/src/linker/view_utils';
import * as import8 from '@angular/core/src/linker/view_type';
import * as import9 from '@angular/core/src/change_detection/change_detection';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
class SharedModuleInjector extends import0.NgModuleInjector<import1.SharedModule> {
  _SharedModule_0:import1.SharedModule;
  __LOCALE_ID_1:any;
  __TRANSLATIONS_FORMAT_2:any;
  constructor(parent:import2.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_1():any {
    if ((this.__LOCALE_ID_1 == (null as any))) { (this.__LOCALE_ID_1 = (null as any)); }
    return this.__LOCALE_ID_1;
  }
  get _TRANSLATIONS_FORMAT_2():any {
    if ((this.__TRANSLATIONS_FORMAT_2 == (null as any))) { (this.__TRANSLATIONS_FORMAT_2 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_2;
  }
  createInternal():import1.SharedModule {
    this._SharedModule_0 = new import1.SharedModule();
    return this._SharedModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SharedModule)) { return this._SharedModule_0; }
    if ((token === import3.LOCALE_ID)) { return this._LOCALE_ID_1; }
    if ((token === import3.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SharedModuleNgFactory:import0.NgModuleFactory<import1.SharedModule> = new import0.NgModuleFactory(SharedModuleInjector,import1.SharedModule);
var renderType_MyFooComponent_Host:import4.RenderComponentType = (null as any);
class _View_MyFooComponent_Host0 extends import5.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import6.AppElement;
  _MyFooComponent_0_4:import1.MyFooComponent;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement) {
    super(_View_MyFooComponent_Host0,renderType_MyFooComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-foo',rootSelector,(null as any));
    this._appEl_0 = new import6.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyFooComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyFooComponent_0_4 = new import1.MyFooComponent();
    this._appEl_0.initComponent(this._MyFooComponent_0_4,[],compView_0);
    compView_0.create(this._MyFooComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.MyFooComponent) && (0 === requestNodeIndex))) { return this._MyFooComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MyFooComponent_Host0(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement):import5.AppView<any> {
  if ((renderType_MyFooComponent_Host === (null as any))) { (renderType_MyFooComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_MyFooComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyFooComponentNgFactory:import11.ComponentFactory<import1.MyFooComponent> = new import11.ComponentFactory<import1.MyFooComponent>('my-foo',viewFactory_MyFooComponent_Host0,import1.MyFooComponent);
const styles_MyFooComponent:any[] = [];
var renderType_MyFooComponent:import4.RenderComponentType = (null as any);
class _View_MyFooComponent0 extends import5.AppView<import1.MyFooComponent> {
  _text_0:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement) {
    super(_View_MyFooComponent0,renderType_MyFooComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'my-foo',(null as any));
    this.init([],[this._text_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_MyFooComponent0(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement):import5.AppView<import1.MyFooComponent> {
  if ((renderType_MyFooComponent === (null as any))) { (renderType_MyFooComponent = viewUtils.createRenderComponentType('/Users/robwormald/Dev/demos/ngmodules-bundling-test/src/components/shared.module.ts class MyFooComponent - inline template',0,import10.ViewEncapsulation.None,styles_MyFooComponent,{})); }
  return new _View_MyFooComponent0(viewUtils,parentInjector,declarationEl);
}
var renderType_MyBarComponent_Host:import4.RenderComponentType = (null as any);
class _View_MyBarComponent_Host0 extends import5.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import6.AppElement;
  _MyBarComponent_0_4:import1.MyBarComponent;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement) {
    super(_View_MyBarComponent_Host0,renderType_MyBarComponent_Host,import8.ViewType.HOST,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import6.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-bar',rootSelector,(null as any));
    this._appEl_0 = new import6.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyBarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyBarComponent_0_4 = new import1.MyBarComponent();
    this._appEl_0.initComponent(this._MyBarComponent_0_4,[],compView_0);
    compView_0.create(this._MyBarComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.MyBarComponent) && (0 === requestNodeIndex))) { return this._MyBarComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MyBarComponent_Host0(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement):import5.AppView<any> {
  if ((renderType_MyBarComponent_Host === (null as any))) { (renderType_MyBarComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_MyBarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyBarComponentNgFactory:import11.ComponentFactory<import1.MyBarComponent> = new import11.ComponentFactory<import1.MyBarComponent>('my-bar',viewFactory_MyBarComponent_Host0,import1.MyBarComponent);
const styles_MyBarComponent:any[] = [];
var renderType_MyBarComponent:import4.RenderComponentType = (null as any);
class _View_MyBarComponent0 extends import5.AppView<import1.MyBarComponent> {
  _text_0:any;
  constructor(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement) {
    super(_View_MyBarComponent0,renderType_MyBarComponent,import8.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import9.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import6.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'my-bar',(null as any));
    this.init([],[this._text_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_MyBarComponent0(viewUtils:import7.ViewUtils,parentInjector:import2.Injector,declarationEl:import6.AppElement):import5.AppView<import1.MyBarComponent> {
  if ((renderType_MyBarComponent === (null as any))) { (renderType_MyBarComponent = viewUtils.createRenderComponentType('/Users/robwormald/Dev/demos/ngmodules-bundling-test/src/components/shared.module.ts class MyBarComponent - inline template',0,import10.ViewEncapsulation.None,styles_MyBarComponent,{})); }
  return new _View_MyBarComponent0(viewUtils,parentInjector,declarationEl);
}