// Code generated by angular2-stress-test

import { NgModule }       from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';
import { AppComponent }   from './app.component';

import { GeneratedComponent000001 } from "./component000001";
import { GeneratedComponent000002 } from "./component000002";
import { GeneratedComponent000003 } from "./component000003";
import { GeneratedComponent000004 } from "./component000004";
import { GeneratedComponent000005 } from "./component000005";
import { GeneratedComponent000006 } from "./component000006";
import { GeneratedComponent000007 } from "./component000007";
import { GeneratedComponent000008 } from "./component000008";
import { GeneratedComponent000009 } from "./component000009";
import { GeneratedComponent000010 } from "./component000010";
import { GeneratedComponent000011 } from "./component000011";
import { GeneratedComponent000012 } from "./component000012";
import { GeneratedComponent000013 } from "./component000013";
import { GeneratedComponent000014 } from "./component000014";
import { GeneratedComponent000015 } from "./component000015";
import { GeneratedComponent000016 } from "./component000016";
import { GeneratedComponent000017 } from "./component000017";
import { GeneratedComponent000018 } from "./component000018";
import { GeneratedComponent000019 } from "./component000019";
import { GeneratedComponent000020 } from "./component000020";
import { GeneratedComponent000021 } from "./component000021";
import { GeneratedComponent000022 } from "./component000022";
import { GeneratedComponent000023 } from "./component000023";
import { GeneratedComponent000024 } from "./component000024";
import { GeneratedComponent000025 } from "./component000025";
import { GeneratedComponent000026 } from "./component000026";
import { GeneratedComponent000027 } from "./component000027";
import { GeneratedComponent000028 } from "./component000028";
import { GeneratedComponent000029 } from "./component000029";
import { GeneratedComponent000030 } from "./component000030";
import { GeneratedComponent000031 } from "./component000031";
import { GeneratedComponent000032 } from "./component000032";
import { GeneratedComponent000033 } from "./component000033";
import { GeneratedComponent000034 } from "./component000034";
import { GeneratedComponent000035 } from "./component000035";
import { GeneratedComponent000036 } from "./component000036";
import { GeneratedComponent000037 } from "./component000037";
import { GeneratedComponent000038 } from "./component000038";
import { GeneratedComponent000039 } from "./component000039";
import { GeneratedComponent000040 } from "./component000040";
import { GeneratedComponent000041 } from "./component000041";
import { GeneratedComponent000042 } from "./component000042";
import { GeneratedComponent000043 } from "./component000043";
import { GeneratedComponent000044 } from "./component000044";
import { GeneratedComponent000045 } from "./component000045";
import { GeneratedComponent000046 } from "./component000046";
import { GeneratedComponent000047 } from "./component000047";
import { GeneratedComponent000048 } from "./component000048";
import { GeneratedComponent000049 } from "./component000049";
import { GeneratedComponent000050 } from "./component000050";


@NgModule({
  declarations: [
    GeneratedComponent000001,
    GeneratedComponent000002,
    GeneratedComponent000003,
    GeneratedComponent000004,
    GeneratedComponent000005,
    GeneratedComponent000006,
    GeneratedComponent000007,
    GeneratedComponent000008,
    GeneratedComponent000009,
    GeneratedComponent000010,
    GeneratedComponent000011,
    GeneratedComponent000012,
    GeneratedComponent000013,
    GeneratedComponent000014,
    GeneratedComponent000015,
    GeneratedComponent000016,
    GeneratedComponent000017,
    GeneratedComponent000018,
    GeneratedComponent000019,
    GeneratedComponent000020,
    GeneratedComponent000021,
    GeneratedComponent000022,
    GeneratedComponent000023,
    GeneratedComponent000024,
    GeneratedComponent000025,
    GeneratedComponent000026,
    GeneratedComponent000027,
    GeneratedComponent000028,
    GeneratedComponent000029,
    GeneratedComponent000030,
    GeneratedComponent000031,
    GeneratedComponent000032,
    GeneratedComponent000033,
    GeneratedComponent000034,
    GeneratedComponent000035,
    GeneratedComponent000036,
    GeneratedComponent000037,
    GeneratedComponent000038,
    GeneratedComponent000039,
    GeneratedComponent000040,
    GeneratedComponent000041,
    GeneratedComponent000042,
    GeneratedComponent000043,
    GeneratedComponent000044,
    GeneratedComponent000045,
    GeneratedComponent000046,
    GeneratedComponent000047,
    GeneratedComponent000048,
    GeneratedComponent000049,
    GeneratedComponent000050,
    AppComponent
  ],
  imports: [BrowserModule],
  bootstrap: [AppComponent]
})
export class AppModule { }
