// Code generated by angular2-stress-test

import { NgModule }       from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';
import { AppComponent }   from './app.component';

import { GeneratedComponent000001 } from "./component000001";
import { GeneratedComponent000002 } from "./component000002";
import { GeneratedComponent000003 } from "./component000003";
import { GeneratedComponent000004 } from "./component000004";
import { GeneratedComponent000005 } from "./component000005";


@NgModule({
  declarations: [
    GeneratedComponent000001,
    GeneratedComponent000002,
    GeneratedComponent000003,
    GeneratedComponent000004,
    GeneratedComponent000005,
    AppComponent
  ],
  imports: [BrowserModule],
  bootstrap: [AppComponent]
})
export class AppModule { }
