// Code generated by angular2-stress-test

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: '<h1>Angular 2 App with 6 components</h1><my-comp-000001></my-comp-000001>'
})
export class AppComponent { }
