// Code generated by angular2-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'my-comp-000004',
  template: `<div>
    <span>component {{myName}}, parent is {{parentName}}</span>
    <div style="padding-left: 5px">
    </div></div>
  `
})
export class GeneratedComponent000004 {
  @Input() parentName: string;
  myName: string = "000004";
}
