// Code generated by angular2-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'my-comp-000001',
  template: `<div>
    <span>component {{myName}}, parent is {{parentName}}</span>
    <div style="padding-left: 5px">
      <my-comp-000002 [parentName]="myName"></my-comp-000002>
      <my-comp-000003 [parentName]="myName"></my-comp-000003>
    </div></div>
  `
})
export class GeneratedComponent000001 {
  @Input() parentName: string;
  myName: string = "000001";
}
