// Code generated by angular2-stress-test

import { Component, Input } from '@angular/core';

@Component({
  selector: 'my-comp-000002',
  template: `<div>
    <span>component {{myName}}, parent is {{parentName}}</span>
    <div style="padding-left: 5px">
      <my-comp-000004 [parentName]="myName"></my-comp-000004>
      <my-comp-000005 [parentName]="myName"></my-comp-000005>
    </div></div>
  `
})
export class GeneratedComponent000002 {
  @Input() parentName: string;
  myName: string = "000002";
}
